# Copyright 2025 Xin Huang
#
# GNU General Public License v3.0
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, please see
#
#    https://www.gnu.org/licenses/gpl-3.0.en.html


import numpy as np
import pandas as pd


n_model = 1
n_rep = 25

np.random.seed(3821)
seed_list = np.random.randint(1, 2**31, n_rep)
cutoffs = np.arange(0.1, 1.0, 0.1).round(1)
cutoffs = np.concatenate([np.array([0.001, 0.01]), cutoffs, np.array([0.99, 0.999])])


rule all:
    input:
        expand(
            "results/gaishi/model_{model_id}/plots/gaishi.model_{model_id}.{type}.pred.pr.curve.png",
            model_id=range(n_model),
            type=["lr", "etc"],
        ),
        expand(
            "results/gaishi/model_{model_id}/plots/gaishi.model_{model_id}.{type}.pred.cutoff_{cutoff}.confusion.matrix.png",
            model_id=range(n_model),
            type=["lr", "etc"],
            cutoff=cutoffs,
        ),


include: "rules/common.smk"
include: "rules/simulation.smk"
include: "rules/gaishi_lr.smk"
include: "rules/gaishi_etc.smk"
